/*
 * Razix Engine HLSL Vertex Shader File
 * Used to render a screen space quad
 */
//------------------------------------------------------------------------------
#include <ShaderInclude.Builtin.ShaderLangCommon.h>
//------------------------------------------------------------------------------
// Vertex Input (None, generated by VS)
// Vertex Shader Stage Output
struct VSOutput
{
    float4 position : SV_POSITION;
    float2 uv : TEXCOORD0;
};

//------------------------------------------------------------------------------
// Main Vertex Shader
VSOutput VS_MAIN(uint vertexID : SV_VertexID)
{
    VSOutput vs_out;

    // Calculate UV coordinates based on vertexID
    float x = float((vertexID << 1) & 2);
    float y = float(vertexID & 2);
    float2 uv = float2(x, y);
    vs_out.uv = uv;

    // Set the final vertex position
    vs_out.position = float4(uv * 2.0f - 1.0f, 0.0f, 1.0f);

    return vs_out;
}
//------------------------------------------------------------------------------
