#version 450
/*
 * Razix Engine GLSL Vertex Shader File
 * Used to render a screen space quad
 */
// https://www.khronos.org/registry/OpenGL/extensions/ARB/ARB_separate_shader_objects.txt Read this for why this extension is enables for all glsl shaders
#extension GL_ARB_separate_shader_objects : enable
// This extension is enabled for additional glsl features introduced after 420 check https://www.khronos.org/registry/OpenGL/extensions/ARB/ARB_shading_language_420pack.txt for more details
#extension GL_ARB_shading_language_420pack : enable
//------------------------------------------------------------------------------
// Vertex Input (None, generated by VS)
//------------------------------------------------------------------------------
// Vertex Shader Stage Output
layout(location = 0) out VSOutput
{
    vec2 uv;
}vs_out;

out gl_PerVertex
{
    vec4 gl_Position;
};
//------------------------------------------------------------------------------
void main()
{
    // Calculate UV coordinates based on gl_VertexID
    float x = float((gl_VertexIndex << 1) & 2);
    float y = float(gl_VertexIndex & 2);
    vec2 uv = vec2(x, y);
    vs_out.uv = uv;
    
    // Set the final vertex position
    gl_Position = vec4(uv * 2.0f - 1.0f, 0.0f, 1.0f);
}
//------------------------------------------------------------------------------
