name: CI Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive
    
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    
    - name: Setup Visual Studio
      uses: microsoft/setup-msbuild@v2
      with:
        msbuild-architecture: x64
    
    - name: Add MSBuild to PATH
      run: |
        $msbuildPath = "${env:ProgramFiles}\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin"
        if (-not (Test-Path $msbuildPath)) {
          $msbuildPath = "${env:ProgramFiles(x86)}\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin"
        }
        if (-not (Test-Path $msbuildPath)) {
          $msbuildPath = "${env:ProgramFiles}\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin"
        }
        if (Test-Path $msbuildPath) {
          echo $msbuildPath | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          echo "MSBuild path added: $msbuildPath"
        } else {
          echo "MSBuild not found in expected locations"
          exit 1
        }
      shell: powershell
    
    - name: Cache Vulkan SDK
      uses: actions/cache@v4
      id: cache-vulkan-windows
      with:
        path: |
          C:\VulkanSDK
        key: vulkan-sdk-windows-1.3.243.0
    
    - name: Prepare Vulkan SDK
      uses: humbletim/setup-vulkan-sdk@v1.2.1
      with:
        vulkan-query-version: 1.3.243.0
        vulkan-components: Vulkan-Headers, Vulkan-Loader
        vulkan-use-cache: true
    
    - name: Generate Project Files
      run: |
        cd Scripts
        .\GenerateVS22.bat
      shell: cmd
    
    - name: Build Engine (GoldMaster)
      run: |
        cd Scripts
        python build_razix.py --platform windows --config GoldMaster --github-ci
      shell: cmd

  build-macos:
    runs-on: macos-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive
    
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    
    - name: Install Xcode Command Line Tools
      run: |
        # Ensure Xcode command line tools are installed
        xcode-select --install || true
        # Accept Xcode license
        sudo xcodebuild -license accept || true
    
    - name: Cache MoltenVK SDK
      uses: actions/cache@v4
      id: cache-vulkan-macos
      with:
        path: |
          ~/VulkanSDK
        key: moltenvk-sdk-macos-1.3.290.0
    
    - name: Install MoltenVK SDK
      if: steps.cache-vulkan-macos.outputs.cache-hit != 'true'
      run: |
        # Download the Vulkan SDK with MoltenVK for macOS
        curl -L -o vulkan-sdk.dmg https://sdk.lunarg.com/sdk/download/1.3.290.0/mac/vulkansdk-macos-1.3.290.0.dmg
        # Mount the DMG
        hdiutil attach vulkan-sdk.dmg -mountpoint /Volumes/VulkanSDK
        # Copy the SDK to a permanent location
        sudo mkdir -p ~/VulkanSDK
        sudo cp -r "/Volumes/VulkanSDK/VulkanSDK/1.3.290.0" ~/VulkanSDK/
        # Unmount the DMG
        hdiutil detach /Volumes/VulkanSDK
        # Clean up
        rm vulkan-sdk.dmg
    
    - name: Setup Vulkan SDK Environment
      run: |
        echo "VULKAN_SDK=$HOME/VulkanSDK/1.3.290.0/macOS" >> $GITHUB_ENV
        echo "$HOME/VulkanSDK/1.3.290.0/macOS/bin" >> $GITHUB_PATH
    
    - name: Generate Project Files
      run: |
        chmod +x ./Scripts/GenerateXCodeProjectsMacOS.sh
        ./Scripts/GenerateXCodeProjectsMacOS.sh
    
    - name: Build Engine (GoldMaster)
      run: |
        python Scripts/build_razix.py --platform macos --config GoldMaster